// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace UrnaEletronica.API.Models
{
    public partial class Candidato
    {
        public Candidato()
        {
            Votos = new HashSet<Votos>();
        }

        [Key]
        public int IdCandidato { get; set; }

        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string NomeCandidato { get; set; }

        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string NomeVice { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime DataCadastro { get; set; }

        public int Legenda { get; set; }

        [InverseProperty("IdCandidatoNavigation")]
        public virtual ICollection<Votos> Votos { get; set; }
    }
}