// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace UrnaEletronica.API.Models
{
    public partial class UrnaEletronicaContext : DbContext
    {
        public UrnaEletronicaContext()
        {
        }

        public UrnaEletronicaContext(DbContextOptions<UrnaEletronicaContext> options)
            : base(options)
        {
        }

        public virtual DbSet<Candidato> Candidato { get; set; }
        public virtual DbSet<Votos> Votos { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Candidato>(entity =>
            {
                entity.HasKey(e => e.IdCandidato)
                    .HasName("PK__Candidat__D55989055C57649C");
            });

            modelBuilder.Entity<Votos>(entity =>
            {
                entity.HasKey(e => e.IdVoto)
                    .HasName("PK__Votos__550D2C7331F32EA6");

                entity.HasOne(d => d.IdCandidatoNavigation)
                    .WithMany(p => p.Votos)
                    .HasForeignKey(d => d.IdCandidato)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_Votos_Candidato");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}